In [64]:
import numpy as np
# Load pandas
import pandas as pd
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import roc_auc_score

In [ ]:
filename = "/Users/maria/Downloads/train_2008.csv"
data = np.loadtxt(filename, skiprows=1, delimiter=',')

# Set random seed
np.random.seed(0)

In [42]:
X_train = (np.asarray(data))[:, 3:382].astype(np.float)
y_train = (np.asarray(data))[:, 382].astype(np.float)

df = pd.DataFrame(data)

# remove first three columns

# rename 382th column to did_vote
df = df.rename(columns={ df.columns[382]: "did_vote" })
df.head()

0     1       2    3      4    5    6    7    8    9  ...  373  374  \
0  16000.0  11.0  2008.0  1.0  201.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   
1  16001.0  11.0  2008.0  1.0  201.0  0.0  2.0  1.0  1.0 -1.0  ...  2.0  2.0   
2  16002.0  11.0  2008.0  1.0    1.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   
3  16003.0  11.0  2008.0  2.0    1.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   
4  16004.0  11.0  2008.0  2.0  201.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   

   375  376  377  378  379  380  381  did_vote  
0  2.0  0.0  0.0  0.0  0.0  0.0  0.0       0.0  
1  2.0  0.0  0.0  0.0  0.0  0.0  0.0       0.0  
2  2.0  0.0  0.0  0.0  0.0  0.0  0.0       0.0  
3  2.0  0.0  0.0  0.0  0.0  0.0  0.0       0.0  
4  2.0  0.0  0.0  0.0  0.0  0.0  0.0       0.0  

[5 rows x 383 columns]

In [43]:
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
df.head()

0     1       2    3      4    5    6    7    8    9  ...  374  375  \
0  16000.0  11.0  2008.0  1.0  201.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   
1  16001.0  11.0  2008.0  1.0  201.0  0.0  2.0  1.0  1.0 -1.0  ...  2.0  2.0   
2  16002.0  11.0  2008.0  1.0    1.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   
3  16003.0  11.0  2008.0  2.0    1.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   
4  16004.0  11.0  2008.0  2.0  201.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   

   376  377  378  379  380  381  did_vote  is_train  
0  0.0  0.0  0.0  0.0  0.0  0.0       0.0      True  
1  0.0  0.0  0.0  0.0  0.0  0.0       0.0      True  
2  0.0  0.0  0.0  0.0  0.0  0.0       0.0      True  
3  0.0  0.0  0.0  0.0  0.0  0.0       0.0     False  
4  0.0  0.0  0.0  0.0  0.0  0.0       0.0      True  

[5 rows x 384 columns]

In [44]:
# Create two new dataframes, one with the training rows, one with the test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]

# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 48641
Number of observations in the test data: 16026


In [62]:
# Create a random forest Classifier. By convention, clf means 'Classifier'
clf = RandomForestRegressor(n_jobs=1, random_state=0)

# Create a list of the feature column's names
features = df.columns[4:382]

y = train["did_vote"]

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(train[features], y)

NameError: name 'RandomForestRegressor' is not defined

In [61]:
# Apply the Classifier we trained to the test data
clf.predict(test[features])[0:50]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [56]:
# View the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[0:10]

array([[ 1. ,  0. ],
       [ 0.6,  0.4],
       [ 0.9,  0.1],
       [ 0.7,  0.3],
       [ 1. ,  0. ],
       [ 0.6,  0.4],
       [ 0.7,  0.3],
       [ 0.3,  0.7],
       [ 0.5,  0.5],
       [ 0.6,  0.4]])

In [50]:
RandomForest(X_train, y_train, X_train)[2]

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [18]:
X_train[0][20:30]

array([  8.30020000e+04,   1.00000000e+00,   1.00000000e+00,
        -1.00000000e+00,  -1.00000000e+00,  -1.00000000e+00,
         4.00000000e+00,   8.60000000e+01,   4.00000000e+00,
         3.80600000e+04])