In [28]:
import numpy as np
# Load pandas
import pandas as pd
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler
mmscaler = MinMaxScaler()



from sklearn.metrics import roc_auc_score

In [3]:
filename = "/Users/maria/CS155/kaggle/data/train_2008.csv"
data = np.loadtxt(filename, skiprows=1, delimiter=',')

# Set random seed
np.random.seed(0)

In [45]:
X_train = (np.asarray(data))[:, 0:382].astype(np.float)
y_train = (np.asarray(data))[:, 382].astype(np.float)

df = pd.DataFrame(data)

In [46]:
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
df.head()

0     1       2    3      4    5    6    7    8    9  ...  374  375  \
0  16000.0  11.0  2008.0  1.0  201.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   
1  16001.0  11.0  2008.0  1.0  201.0  0.0  2.0  1.0  1.0 -1.0  ...  2.0  2.0   
2  16002.0  11.0  2008.0  1.0    1.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   
3  16003.0  11.0  2008.0  2.0    1.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   
4  16004.0  11.0  2008.0  2.0  201.0  0.0  1.0  1.0  1.0 -1.0  ...  2.0  2.0   

   376  377  378  379  380  381  382  is_train  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      True  
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0      True  
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0      True  
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0      True  
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0      True  

[5 rows x 384 columns]

In [47]:
# Create two new dataframes, one with the training rows, one with the test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]

# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 48413
Number of observations in the test data: 16254


In [48]:
# Create a random forest Classifier. By convention, clf means 'Classifier'
# clf = RandomForestRegressor(n_jobs=1, random_state=0)
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
    
X_train = mmscaler.fit_transform(X_train)

# Create a list of the feature column's names
features = train.columns[4:382]

y = train["did_vote"]
x = train[features]

#clf.fit(train[features], y)

test = SelectKBest(score_func=f_regression, k=10)
fit = test.fit(X_train, y_train)

np.set_printoptions(precision=3)
# print(fit.scores_)
features = fit.transform(X_train)

cols = test.get_support(indices=True)

train = train[cols]

print(features[0:10,:])

KeyError: 'did_vote'

In [ ]:
train

In [33]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
rfe = RFE(model, 3)
fit = rfe.fit(X_train, y_train)
print("Num Features: %d") % fit.n_features_
print("Selected Features: %s") % fit.support_
print("Feature Ranking: %s") % fit.ranking_

KeyboardInterrupt: 

In [61]:
# Apply the Classifier we trained to the test data
clf.predict(test[features])[0:50]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [56]:
# View the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[0:10]

array([[ 1. ,  0. ],
       [ 0.6,  0.4],
       [ 0.9,  0.1],
       [ 0.7,  0.3],
       [ 1. ,  0. ],
       [ 0.6,  0.4],
       [ 0.7,  0.3],
       [ 0.3,  0.7],
       [ 0.5,  0.5],
       [ 0.6,  0.4]])

In [50]:
RandomForest(X_train, y_train, X_train)[2]

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [18]:
X_train[0][20:30]

array([  8.30020000e+04,   1.00000000e+00,   1.00000000e+00,
        -1.00000000e+00,  -1.00000000e+00,  -1.00000000e+00,
         4.00000000e+00,   8.60000000e+01,   4.00000000e+00,
         3.80600000e+04])