In [26]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Flatten, Dropout

def load_data(filename, skiprows = 1):
    '''   
    Function loads data stored in the file filename and returns it as a numpy ndarray.\n",

    Inputs:
    filename: given as a string.
    Outputs:\n",
    Data contained in the file, returned as a numpy ndarray\n",
    '''
    return np.loadtxt(filename, skiprows=skiprows, delimiter=',')

Using TensorFlow backend.


In [166]:
from keras import backend as k_back


# define the AUC metric being used in the competition
# this function can be used in Keras' Sequential Model compilation only
def auc(y_true, y_pred):
    auc = tf.metrics.auc(y_true, y_pred)[1]
    k_back.get_session().run(tf.local_variables_initializer())
    return auc

In [204]:
train = load_data("data/train_2008.csv")
test = load_data("data/test_2008.csv")


In [18]:
y_train_new = train[:,train.shape[1]-1:]

In [110]:
def refineInput(X, y_train_new, section, total):
    X_traincopy = X.copy()
    y_traincopy = y_train_new.copy()
    X_train = X_traincopy[:,3:]
    num = X_traincopy.shape[0]/total
    X_test = X_traincopy[int(num*section):int(num*(section+1)),:]
    X_train = X_traincopy[:int(num*section),:]
    X_train = np.concatenate((X_train, X_traincopy[int(num*(section+1)):,:]))
    
    y_test = y_traincopy[int(num*section):int(num*(section+1)),:]
    y_train = y_traincopy[:int(num*section),:]
    y_train = np.concatenate((y_train, y_traincopy[int(num*(section+1)):,:]))
    
    return X_train, X_test, y_train, y_test

In [108]:
X_train[10:12,:]

array([[ 1.8405000e+04,  1.1000000e+01,  2.0080000e+03,  1.0000000e+00,
         2.0100000e+02,  0.0000000e+00,  2.0000000e+00,  1.0000000e+00,
         1.0000000e+00, -1.0000000e+00,  1.0000000e+00, -2.0000000e+00,
        -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,  4.3738474e+07,
         1.0000000e+00,  5.0000000e+00,  4.0000000e+00,  5.0000000e+00,
         2.0000000e+00,  1.0000000e+00,  3.0000000e+00,  8.3001000e+04,
         2.0000000e+00, -1.0000000e+00, -1.0000000e+00, -1.0000000e+00,
        -1.0000000e+00,  2.0000000e+00,  3.3000000e+01,  1.7000000e+01,
         1.9500000e+04,  1.1500000e+02,  4.0000000e+00,  1.0000000e+00,
         0.0000000e+00,  2.0000000e+00,  0.0000000e+00,  1.0000000e+00,
         4.0000000e+00,  1.8000000e+01,  0.0000000e+00,  6.0000000e+00,
        -1.0000000e+00,  2.0000000e+00,  2.0000000e+00,  2.0000000e+00,
         3.9000000e+01,  2.0000000e+00, -1.0000000e+00,  9.0000000e+00,
         1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.00000

In [ ]:
model = Sequential([
    #Flatten(input_shape=(28,28,)),  # Use np.reshape instead of this in hw\n",
    Dense(1050, input_shape=(382,)), 
    Activation('relu'), 
    Dropout(0.3),        
    Dense(1),
    Activation('softmax')
    ])
model.compile(loss='squared_hinge',optimizer='adam', metrics=['accuracy'], verbose=1)
model.build()
    
model.summary()
fit = model.fit(X_train, y_train_new, batch_size=32, epochs=3, verbose = 1)
## Printing the accuracy of our model, according to the loss function specified in model.compile above\n",
score = model.evaluate(X_train, y_train_new)
print(score)

predict = model.predict(X_train)




_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_22 (Dense)             (None, 1050)              402150    
_________________________________________________________________
activation_22 (Activation)   (None, 1050)              0         
_________________________________________________________________
dropout_15 (Dropout)         (None, 1050)              0         
_________________________________________________________________
dense_23 (Dense)             (None, 1)                 1051      
_________________________________________________________________
activation_23 (Activation)   (None, 1)                 0         
Total params: 403,201
Trainable params: 403,201
Non-trainable params: 0
_________________________________________________________________
Epoch 1/10
64667/64667 [==============================] - 25s 384us/step - loss: 0.7446 - acc: 0.2554
Epoch 2/10
64667/64667 [==========

In [141]:
X_train = train[:,:train.shape[1]-1]
#X_train = X_train[:,3:]
score = model.evaluate(X_train, y_train_new)
print(score)

64667/64667 [==============================] - 6s 88us/step
[0.7446147184799109, 0.25538528152008916]


array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [171]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.metrics import roc_auc_score

N = 7
for i in range(7):
    y_train_new = train[:,train.shape[1]-1:]
    X_train = train[:,:train.shape[1]-1]
    X_train, x_test, y_train, y_test = refineInput(X_train, y_train_new, i, 7)
    # Fit regression model
    regr_1 = DecisionTreeRegressor(max_depth=7)
    regr_2 = DecisionTreeRegressor(max_depth=10)
    regr_1.fit(X_train, y_train)
    regr_2.fit(X_train, y_train)

    # Predict
    y_1 = regr_1.predict(x_test)
    y_2 = regr_2.predict(x_test)
    
    y_t_1 = regr_1.predict(X_train)
    y_t_2 = regr_2.predict(X_train)
    
    
    print("test", roc_auc_score(y_test, y_1))
    print(roc_auc_score(y_test, y_2)  )
    
    print("train", roc_auc_score(y_train ,y_t_1 ))
    print(roc_auc_score(y_train,y_t_2)  )


(55429, 382) (55429, 1)
test 0.24569092497610678
0.2724278963027511
train 0.22834767175919446
0.18382215233471133
(55429, 382) (55429, 1)
test 0.24093237515124077
0.2681201444441733
train 0.23018821503929998
0.19051035161426588
(55429, 382) (55429, 1)
test 0.25700321766530987
0.2778615252214859
train 0.22652252366797798
0.18272851154799685
(55429, 382) (55429, 1)
test 0.245460970566455
0.2685809975186084
train 0.2296259653046281
0.18563403573404924
(55429, 382) (55429, 1)
test 0.25148736244195025
0.2596522686880114
train 0.2281081888271741
0.18682707332699167
(55429, 382) (55429, 1)
test 0.2436451850078395
0.26706897174306
train 0.22927443062407538
0.1870351438697503
(55428, 382) (55428, 1)


KeyboardInterrupt: 

In [176]:
from sklearn.ensemble import RandomForestRegressor

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error


N = 7
res = []
for depth in range(1, 10):
    row = []
    for nodes in range(2, 10):
        avg_test = 0
        avg_train = 0
        for i in range(7):
            y_train_new = train[:,train.shape[1]-1:]
            X_train = train[:,:train.shape[1]-1]
            X_train, x_test, y_train, y_test = refineInput(X_train, y_train_new, i, 7)
            # Fit regression model
            y_train = np.ravel(y_train)
            regr_1 = RandomForestRegressor(max_depth=depth, max_leaf_nodes = nodes)
            regr_1.fit(X_train, y_train)
            #regr_2.fit(X_train, y_train)

            # Predict
            y_1 = regr_1.predict(x_test)
            #y_2 = regr_2.predict(x_test)

            y_t_1 = regr_1.predict(X_train)
            #y_t_2 = regr_2.predict(X_train)

            avg_test += roc_auc_score(y_test, y_1)
            avg_train += roc_auc_score(y_train ,y_t_1 )
            #print("test", roc_auc_score(y_test, y_1))
            #print(roc_auc_score(y_test, y_2)  )

            #print("train", roc_auc_score(y_train ,y_t_1 ))
            #print(roc_auc_score(y_train,y_t_2)  )
        avg_test /= 7
        avg_train /= 7
        row.append(avg_test)
        print(avg_test)
    res.append(row)
    


(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55428, 382) (55428, 1)
0.6495285165738481
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55428, 382) (55428, 1)
0.67265743304632
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55428, 382) (55428, 1)
0.7105775482162505
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55428, 382) (55428, 1)
0.7111891221547529
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55428, 382) (55428, 1)
0.7106737243649933
(55429, 382) (55429, 1)
(55429, 382) (55429, 1)
(55429, 382) (55429

KeyboardInterrupt: 

In [69]:
from sklearn.metrics import mean_squared_error


0.054374085090559646
0.13803736922642404


In [206]:
X_test


array([], shape=(16000, 0), dtype=float64)

In [155]:
X_test = test[:,3:]
y_train_new = train[:,train.shape[1]-1:]
X_train = train[:,:train.shape[1]-1]
X_train = X_train[:,3:]
#regr_2 = DecisionTreeRegressor(max_depth=10)
#regr_2.fit(X_train, y_train_new)
#y_2 = regr_2.predict(X_test)

In [219]:
test = load_data("data/test_2008.csv")

from sklearn.preprocessing import MinMaxScaler
X_test = test[:,3:]
predictions = xgb.predict(X_test)
predictions = predictions.reshape(16000, 1)

mmscaler = MinMaxScaler()
new_pred = mmscaler.fit_transform(predictions)
ids = test[:,:1]
ids = ids.astype(int)
new_pred = new_pred.astype(float)
test = np.concatenate((ids, predictions), axis=1)

In [226]:

predictions = predictions.astype(float)
test = np.concatenate((ids, predictions), axis=1)

In [227]:
np.savetxt('submission.csv', test, delimiter=',', fmt='%1.10f', header = 'id,target')

In [225]:
print(predictions)
print(new_pred)
for i in predictions:
    if i[0] <0:
        i[0] = 0
    elif i[0]>1:
        i[0] = 1
        
print(min(predictions))

[[0.27371597]
 [0.11366704]
 [0.1329549 ]
 ...
 [0.24748915]
 [0.02386603]
 [0.2097044 ]]
[[0.29579499]
 [0.15811621]
 [0.17470819]
 ...
 [0.27323392]
 [0.08086675]
 [0.24073036]]
[0.]


In [201]:
import xgboost

from sklearn import cross_validation, tree, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import explained_variance_score
xgb = xgboost.XGBRegressor(n_estimators=100, learning_rate=0.08, gamma=0, subsample=0.75,
                           colsample_bytree=1, max_depth=7)

y_train_new = train[:,train.shape[1]-1:]
X_train = train[:,:train.shape[1]-1]
    
X_test = test[:,3:]
y_train_new = train[:,train.shape[1]-1:]
X_train = train[:,:train.shape[1]-1]
X_train = X_train[:,3:]

#X_train, X_test, y_train, y_test = cross_validation.train_test_split(X_train, y_train_new,test_size=0.2)

xgb.fit(X_train, y_train_new)


#print(roc_auc_score(B, y_test))




ValueError: feature_names mismatch: ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36', 'f37', 'f38', 'f39', 'f40', 'f41', 'f42', 'f43', 'f44', 'f45', 'f46', 'f47', 'f48', 'f49', 'f50', 'f51', 'f52', 'f53', 'f54', 'f55', 'f56', 'f57', 'f58', 'f59', 'f60', 'f61', 'f62', 'f63', 'f64', 'f65', 'f66', 'f67', 'f68', 'f69', 'f70', 'f71', 'f72', 'f73', 'f74', 'f75', 'f76', 'f77', 'f78', 'f79', 'f80', 'f81', 'f82', 'f83', 'f84', 'f85', 'f86', 'f87', 'f88', 'f89', 'f90', 'f91', 'f92', 'f93', 'f94', 'f95', 'f96', 'f97', 'f98', 'f99', 'f100', 'f101', 'f102', 'f103', 'f104', 'f105', 'f106', 'f107', 'f108', 'f109', 'f110', 'f111', 'f112', 'f113', 'f114', 'f115', 'f116', 'f117', 'f118', 'f119', 'f120', 'f121', 'f122', 'f123', 'f124', 'f125', 'f126', 'f127', 'f128', 'f129', 'f130', 'f131', 'f132', 'f133', 'f134', 'f135', 'f136', 'f137', 'f138', 'f139', 'f140', 'f141', 'f142', 'f143', 'f144', 'f145', 'f146', 'f147', 'f148', 'f149', 'f150', 'f151', 'f152', 'f153', 'f154', 'f155', 'f156', 'f157', 'f158', 'f159', 'f160', 'f161', 'f162', 'f163', 'f164', 'f165', 'f166', 'f167', 'f168', 'f169', 'f170', 'f171', 'f172', 'f173', 'f174', 'f175', 'f176', 'f177', 'f178', 'f179', 'f180', 'f181', 'f182', 'f183', 'f184', 'f185', 'f186', 'f187', 'f188', 'f189', 'f190', 'f191', 'f192', 'f193', 'f194', 'f195', 'f196', 'f197', 'f198', 'f199', 'f200', 'f201', 'f202', 'f203', 'f204', 'f205', 'f206', 'f207', 'f208', 'f209', 'f210', 'f211', 'f212', 'f213', 'f214', 'f215', 'f216', 'f217', 'f218', 'f219', 'f220', 'f221', 'f222', 'f223', 'f224', 'f225', 'f226', 'f227', 'f228', 'f229', 'f230', 'f231', 'f232', 'f233', 'f234', 'f235', 'f236', 'f237', 'f238', 'f239', 'f240', 'f241', 'f242', 'f243', 'f244', 'f245', 'f246', 'f247', 'f248', 'f249', 'f250', 'f251', 'f252', 'f253', 'f254', 'f255', 'f256', 'f257', 'f258', 'f259', 'f260', 'f261', 'f262', 'f263', 'f264', 'f265', 'f266', 'f267', 'f268', 'f269', 'f270', 'f271', 'f272', 'f273', 'f274', 'f275', 'f276', 'f277', 'f278', 'f279', 'f280', 'f281', 'f282', 'f283', 'f284', 'f285', 'f286', 'f287', 'f288', 'f289', 'f290', 'f291', 'f292', 'f293', 'f294', 'f295', 'f296', 'f297', 'f298', 'f299', 'f300', 'f301', 'f302', 'f303', 'f304', 'f305', 'f306', 'f307', 'f308', 'f309', 'f310', 'f311', 'f312', 'f313', 'f314', 'f315', 'f316', 'f317', 'f318', 'f319', 'f320', 'f321', 'f322', 'f323', 'f324', 'f325', 'f326', 'f327', 'f328', 'f329', 'f330', 'f331', 'f332', 'f333', 'f334', 'f335', 'f336', 'f337', 'f338', 'f339', 'f340', 'f341', 'f342', 'f343', 'f344', 'f345', 'f346', 'f347', 'f348', 'f349', 'f350', 'f351', 'f352', 'f353', 'f354', 'f355', 'f356', 'f357', 'f358', 'f359', 'f360', 'f361', 'f362', 'f363', 'f364', 'f365', 'f366', 'f367', 'f368', 'f369', 'f370', 'f371', 'f372', 'f373', 'f374', 'f375', 'f376', 'f377', 'f378'] []
expected f138, f3, f372, f283, f270, f0, f285, f189, f228, f125, f142, f290, f100, f39, f131, f27, f223, f84, f32, f281, f309, f280, f59, f98, f278, f259, f145, f73, f119, f211, f41, f203, f250, f307, f105, f217, f164, f5, f22, f135, f25, f21, f102, f86, f184, f359, f109, f15, f361, f71, f330, f180, f128, f114, f196, f92, f120, f284, f53, f200, f364, f368, f374, f51, f95, f267, f188, f305, f231, f122, f323, f78, f50, f261, f91, f107, f319, f121, f67, f327, f242, f28, f87, f143, f148, f80, f178, f4, f258, f300, f191, f249, f170, f2, f150, f64, f89, f19, f99, f253, f192, f350, f48, f224, f141, f334, f336, f166, f256, f101, f234, f240, f357, f333, f110, f265, f213, f58, f177, f8, f154, f54, f326, f317, f195, f351, f30, f35, f115, f56, f33, f241, f162, f373, f147, f311, f106, f79, f12, f132, f113, f172, f69, f42, f208, f210, f219, f252, f173, f260, f335, f254, f308, f62, f45, f339, f9, f273, f43, f153, f313, f157, f190, f182, f232, f146, f341, f318, f201, f151, f130, f206, f238, f183, f140, f179, f245, f47, f72, f13, f299, f315, f10, f163, f83, f276, f60, f370, f174, f197, f371, f124, f226, f248, f358, f23, f332, f257, f306, f94, f176, f202, f272, f169, f329, f74, f321, f158, f346, f310, f215, f230, f175, f159, f225, f61, f363, f117, f181, f63, f289, f343, f156, f34, f293, f365, f301, f149, f292, f152, f322, f46, f126, f255, f352, f275, f160, f31, f251, f186, f212, f355, f239, f353, f324, f194, f198, f77, f137, f136, f236, f312, f16, f279, f376, f246, f286, f75, f88, f112, f337, f18, f96, f76, f68, f316, f44, f347, f139, f243, f244, f269, f123, f129, f302, f354, f29, f81, f40, f6, f108, f298, f277, f378, f161, f111, f199, f185, f168, f304, f144, f207, f17, f297, f375, f14, f205, f38, f65, f274, f55, f303, f165, f52, f227, f66, f216, f90, f287, f36, f320, f247, f127, f235, f104, f214, f167, f70, f233, f20, f314, f366, f237, f268, f1, f193, f204, f362, f340, f37, f222, f85, f218, f103, f133, f294, f118, f82, f344, f187, f367, f171, f263, f11, f93, f221, f377, f49, f338, f348, f342, f134, f209, f295, f288, f369, f220, f262, f57, f266, f7, f356, f271, f296, f282, f264, f360, f97, f291, f345, f26, f229, f328, f325, f155, f116, f349, f24, f331 in input data

In [203]:
X_test

array([], shape=(16000, 0), dtype=float64)

In [153]:
from sklearn.neural_network import MLPRegressor
nn = MLPRegressor()

y_train = np.ravel(y_train)
nn.fit(X_train, y_train)
nn.score(X_train, y_train)

-23412360736.750458

In [152]:
y_train.shape

(51733, 1)

In [182]:
from sklearn import neighbors

y_train_new = train[:,train.shape[1]-1:]
X_train = train[:,:train.shape[1]-1]
    
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X_train, y_train_new,test_size=0.2)
n_neighbors = 10000
knn = neighbors.KNeighborsRegressor(n_neighbors)
y_ = knn.fit(X_train, y_train).predict(X_test)

for i in range(10):
    print(y_[i], y_test[i])

print(roc_auc_score(y_test,y_)  )
    
    
    

[0.246] [0.]
[0.2556] [0.]
[0.2614] [0.]
[0.2691] [0.]
[0.2423] [0.]
[0.2643] [0.]
[0.2394] [0.]
[0.256] [0.]
[0.25] [0.]
[0.2477] [1.]
0.5141380755005418


In [183]:
from sklearn.svm import SVR

y_train_new = train[:,train.shape[1]-1:]
X_train = train[:,:train.shape[1]-1]
    
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X_train, y_train_new,test_size=0.2)


clf = SVR(kernel='poly')
clf.fit(X_train, y_train) 

/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


KeyboardInterrupt: 

In [ ]:
clf.predict(X_test)


In [228]:
xgprediction = predictions.copy()


In [237]:
xgprediction

array([[0.27371597],
       [0.11366704],
       [0.1329549 ],
       ...,
       [0.24748915],
       [0.02386603],
       [0.2097044 ]])

In [229]:
import csv
nn = []
with open('nn.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')
    for row in spamreader:
        nn.append(row[1])

In [233]:
nn_prediction = np.array(nn)

In [236]:
nn_prediction = nn_prediction.astype(float)


array([0.30951509, 0.13851742, 0.14212674, ..., 0.22869109, 0.12686066,
       0.30474904])

In [238]:
nn_prediction = np.reshape(nn_prediction, (-1, 1))

In [239]:
nn_prediction

array([[0.30951509],
       [0.13851742],
       [0.14212674],
       ...,
       [0.22869109],
       [0.12686066],
       [0.30474904]])

In [242]:
merger = (nn_prediction + xgprediction)/2

In [243]:
test = np.concatenate((ids, merger), axis=1)
np.savetxt('submission.csv', test, delimiter=',', fmt='%1.10f', header = 'id,target')